### ISSUE TITLE
Simple request enhancement for membership_starttime

### ISSUE THREAD

**Issue by davidfavor** [strangerstudios/pmpro-import-users-from-csv#13]
If starttime includes (), then starttime pass as-is, rather than enclosing in quotes.

This allows passing NOW(), rather than hard coded times.

Another nice perk would be to pass SYNC(), which set starttime to wp_users user_registered time.

Thanks for your consideration.

**Comment by kimcoleman** [comment]
We do not plan to support this at this time.
