### ISSUE TITLE
The corresponding to member order is not created if no `subscription_transaction_id` is provided

### ISSUE THREAD

**Issue by argysamo** [strangerstudios/pmpro-import-users-from-csv#15]
It took me a lot of time to cope with this issue. 
I tried to import existing members from a csv file . 
The member list was successfully populated. 
However, the order table was not updated, even though I provided all required fields. 

After many attempts I decided to have a look on the code. 
The issue is in the following line:
https://github.com/strangerstudios/pmpro-import-users-from-csv/blob/2102bf0c559e452155dd636d2c6c141d4ce4ff93/pmpro-import-users-from-csv.php#L210

As not all orders have a `subscription_transaction_id` (i.e. they are not recurring), this condition hinders import functionality.

**Comment by ideadude** [comment]
Thanks for the PR. This makes sense. If a gateway is set/etc, the importer wants an order in the DB. I'm going to just remove the line vs commenting it out. Update should go out soon.
