### ISSUE TITLE
No option to Import from CSV

### ISSUE THREAD

**Issue by HenryWaterfall** [strangerstudios/pmpro-import-users-from-csv#2]
Hi I added this as a comment to a previous issue. I haven't seen a response so thought I would add a fresh post.

I have just installed pmpro-import-users-from-csv with Memberships Pro and do not see an option to Import from CSV under users.

Would really appreciate some feeedback, even if it is a not supported anymore so I can find a different solution.

KR,

HWA.

**Comment by TheHandsomeCoder** [comment]
Henry I seem to be getting the same issue as yourself as I keep getting silent errors when importing users. Did you solve your error in the end?

**Comment by zerotigerds** [comment]
there is a note on http://www.paidmembershipspro.com/add-ons/third-party-integration/pmpro-import-users-csv/ about failed imports. reads:  If you have any unused column headers after filling out the template, delete them or your import will fail.

**Comment by dkeil1** [comment]
I am testing this plugin and absolutely need a bulk import for groups of people being added to a members level.

I have all three plugins installed. I have only added the membership_id heading with a number under it to the sample download .csv. Only getting errors.

I can upload the sample .csv from the upload users csv plugin successfully, but the moment I add a member heading, it fails.

I'm doing this on a basic install, minimal plugins for testing purposes using 2105 theme.

Any help would be appreciated. I would certainly be willing to upgrade to pro If I choose to use this plugin, which would be great as it integrates with woo and wpcourseware... would be great if I could get this one thing to work.

Hope there's help for this.
