### ISSUE TITLE
BUG: PMPro Import Users From CSV Template is in an incompatible format

### ISSUE THREAD

**Issue by tictag** [strangerstudios/pmpro-import-users-from-csv#23]
The PMPro Import Users From CSV Template available on the PMPro website (https://www.paidmembershipspro.com/add-ons/pmpro-import-users-csv/) is in an incompatible format for importing users into PMPro using the Import Users from CSV Integration Add On.

The file (import.csv) has EOL configured for CR only, this caused the import to fail. Changing the EOL configuration to CRLR fixes the problem.

Please see attached screenshots.
![2019-10-25_11-48-58](https://user-images.githubusercontent.com/12136834/67566314-60b48180-f71f-11e9-9848-26d620049f99.png)
![2019-10-25_11-49-21](https://user-images.githubusercontent.com/12136834/67566324-6742f900-f71f-11e9-9cdc-e12ed5139695.png)

**Comment by andrewlimaza** [comment]
I highly recommend using Google Sheets when working with CSV's over other programs, personally it's been the most reliable for me.

Thanks for sharing this with us, I will keep this issue open for a bit.
