### ISSUE TITLE
BUG: Neither membership_startdate nor membership_enddate is imported

### ISSUE THREAD

**Issue by tictag** [strangerstudios/pmpro-import-users-from-csv#24]
Neither `membership_startdate` nor `membership_enddate` are imported using the Import Users from CSV Integration Add On.

**STEPS TO RE-CREATE**
1. Download PMPro Import Users From CSV Template from https://www.paidmembershipspro.com/add-ons/pmpro-import-users-csv/
_Note: Refer to https://github.com/strangerstudios/pmpro-import-users-from-csv/issues/23_
2. Remove all unnecessary fields leaving only `user_email` or `user_login` to identify the user account and `membership_startdate` and/or `membership_enddate`
_Note: Ensure correct format: YYYY-MM-DD_
3. Import the CSV using the Import Users from CSV Plugin

The import will return as successful but neither field in table `pmpro_memberships_users` is actually modified.

A workaround is to manually update these fields using the `is_iu_post_user_import` hook:

https://gist.github.com/tictag/a94b5ff707efbc02b34700edbb77051a

**Comment by tictag** [comment]
**FOR PMPRO MODS:** Tickets:
https://www.paidmembershipspro.com/forums/topic/bug-import-users-from-csv-integration-add-on-startdate-unchanged-after-import/
https://www.paidmembershipspro.com/forums/topic/help-how-to-mass-cancel-memberships/

...relate to this issue.

**Comment by andrewlimaza** [comment]
I have run some tests, a couple of years later, and it's working. I am going to close this ticket as it seems to have been resolved.
