### ISSUE TITLE
Import OK but no membership assigned

### ISSUE THREAD

**Issue by southernsons** [strangerstudios/pmpro-import-users-from-csv#32]
Hello,

I have created a csv file with the following information: 

user_login,user_email,first_name,last_name,display_name,role,membership_id,membership_initial_payment,membership_billing_amount,membership_cycle_number,membership_cycle_period,membership_status,membership_startdate,membership_enddate

The CSV plugin does not show any error messages and claims the import was OK.
But when I check the user in Wordpress -> All Users there is no membership level assigned. Also under members in PMPRO the transaction does not appear.

What am I doing wrong?

**Comment by andrewlimaza** [comment]
Please can you open a support ticket on https://www.paidmembershipspro.com so we may assist you further in troubleshooting this.

Github is primarily used for logging bug issues and not support related questions.

Thank you for understanding.
