### ISSUE TITLE
Membership info not uploading

### ISSUE THREAD

**Issue by rozevans** [strangerstudios/pmpro-import-users-from-csv#4]
Hi

I have all three of the plug ins installed, but when I upload a user, it does not include any membership level information for them.

This is like the info included in my CSV

user_login, user_email, user_pass, display_name, role, membership_id, membership_startdate, membership_enddate,

Username, email@email.co.uk, password, Name name, Customer, 3, 01/10/2014, 07/11/2015,

Thanks in advance for your help.

Roz

**Comment by thefill** [comment]
Same issue here

**Comment by ludoviclabbe** [comment]
This add-on doesn't run for me.
