### ISSUE TITLE
Feature Request: Import expired level as level history

### ISSUE THREAD

**Issue by ipokkel** [strangerstudios/pmpro-import-users-from-csv#42]
When the import CSV has a membership level for a user but the set end date is in the past a membership level is not assigned as it already expired.

The ability to add such an expired level during import to the user's level and order history could be helpful to verify that an imported user had a level in the past. This may also be helpful being able to view a user's last active level when migrations are done.

**Comment by kimcoleman** [comment]
We do not plan to support this. The workaround will be for users to rather import their data into the database directly.
